#!/usr/bin/env python3
"""
Generic fixed-target hold demo.

Purpose:
  Test whether the MuJoCo-side joint-impedance layer can hold a fixed arm pose
  under gravity. The target is generated by solving IK for a TCP pose that
  places the carried SFP tip above the NIC-board port entrance.

Frame convention:
  ``A_T_B`` means "pose of frame B with respect to frame A"; it maps a point
  expressed in B into A.

Important scene frame names:
  ``sfp_port_0_link_entrance``:
    port entrance body; this is the desired SFP-tip frame basis.
  ``gripper_tcp``:
    MuJoCo site corresponding to the AIC/Tesseract ``gripper/tcp`` IK target.
  ``ati/tool_link``:
    robot-side tool body.
  ``lc_plug_link``:
    weld child body for the held plug/cable subtree.
  ``sfp_tip_link``:
    SFP plug tip body that should line up with the port entrance.
  ``cable_end_0`` / ``cable_end_0_free``:
    payload root body/freejoint. After IK, the freejoint is moved so the visible
    plug agrees with the kinematic SFP-tip target.

Correct pre-insertion transform chain:
  The initial free-body cable pose in the XML may not already satisfy the weld,
  so do not derive ``tcp_T_sfp_tip`` directly from the raw current
  ``world_T_tcp`` and ``world_T_sfp_tip``. Instead derive it from topology:

    ``tool_T_tcp = inv(world_T_tool) @ world_T_tcp``

    ``weld_child_T_sfp_tip =
        inv(world_T_weld_child) @ world_T_sfp_tip``

    ``tcp_T_sfp_tip =
        inv(tool_T_tcp) @ tool_T_weld_child @ weld_child_T_sfp_tip``

  where ``tool_T_weld_child`` comes from the MuJoCo weld equality between
  ``ati/tool_link`` and ``lc_plug_link``.

Desired SFP-tip pose:
  The pre-insertion target uses the port entrance orientation and shifts upward
  in world Z:

    ``desired_world_T_sfp_tip = world_T_port``

    ``desired_world_T_sfp_tip.p.z += preinsert_height``

IK target:
  ``EnsemblRobot.ComputeIK`` targets ``gripper/tcp``, so convert the desired
  SFP-tip pose into a TCP pose before calling IK:

    ``desired_world_T_tcp =
        desired_world_T_sfp_tip @ inv(tcp_T_sfp_tip)``

  The AIC robot model is expressed in base coordinates. Align MuJoCo world to
  the EnsemblRobot base at ``ik_home_q``:

    ``world_T_base = world_T_tcp_home @ inv(base_T_tcp_home)``

    ``desired_base_T_tcp =
        inv(world_T_base) @ desired_world_T_tcp``

  Then choose the IK solution closest to ``ik_home_q``.

Fresh run from a new ``aic_eval`` distrobox terminal:

  cd /home/rmalhan/Software/ws_aic/src/aic
  pixi shell
  source /opt/ros/kilted/setup.bash
  source /home/rmalhan/Software/ws_aic/install/setup.bash
  export PYTHONNOUSERSITE=1
  export MUJOCO_PLUGIN_PATH=/home/rmalhan/Software/ws_aic/install/opt/mujoco_vendor/lib

  PYTHONPATH=/home/rmalhan/Software/ws_aic/src/aic/aic_utils/aic_mujoco:/home/rmalhan/Software/ws_aic/src/aic/aic_model \
  python3 aic_utils/aic_mujoco/scripts/hold_fixed_target.py \
    --xml /home/rmalhan/Software/ws_aic/src/aic/aic_utils/aic_mujoco/mjcf/scene.xml

For a shorter run:

  add ``--duration 10``

The config supplies the robot joints, passive gripper behavior, controller
gains, and default pre-insertion frame names. ROS is sourced only so
EnsemblRobot can find robot description packages for reset IK; no ROS nodes are
launched.
"""

from __future__ import annotations

import argparse
import time
from pathlib import Path

import mujoco
import mujoco.viewer
import numpy as np

from aic_mujoco.config import load_json_config
from aic_mujoco.joints import (
    JointGroup,
    PassiveJointGroup,
    TorqueMode,
    print_model_summary,
)
from aic_mujoco.controllers import (
    JointImpedanceConfig,
    JointImpedanceController,
    JointTarget,
)
from aic_mujoco.utils import (
    compute_preinsert_joint_target,
    print_transform,
)

SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_CONFIG_PATH = SCRIPT_DIR.parent / "configs" / "experiments" / "hold_preinsert.json"


def print_preinsert_diagnostics(
    diagnostics: dict[str, np.ndarray | str | float | int | None],
) -> None:
    def transform(key: str) -> np.ndarray:
        value = diagnostics[key]
        if not isinstance(value, np.ndarray):
            raise TypeError(f"Expected diagnostic transform {key!r}, got {type(value)}")
        return value

    desired_world_T_sfp_tip = transform("desired_world_T_sfp_tip")
    virtual_world_T_sfp_tip = transform("virtual_world_T_sfp_tip")
    actual_world_T_sfp_tip = transform("actual_world_T_sfp_tip_after_payload_set")

    print("Pre-insertion IK request:")
    for key in (
        "port_body",
        "tcp_site",
        "sfp_tip_body",
        "tool_body",
        "weld_child_body",
        "tcp_T_sfp_tip_source",
        "payload_root_body",
        "payload_root_freejoint",
        "height",
        "solution_count",
    ):
        print(f"  {key}: {diagnostics[key]}")
    print(f"  desired_world_p_sfp_tip: {desired_world_T_sfp_tip[:3, 3].tolist()}")
    print(f"  desired_world_p_tcp: {transform('desired_world_T_tcp')[:3, 3].tolist()}")
    print(f"  desired_base_p_tcp: {transform('desired_base_T_tcp')[:3, 3].tolist()}")

    for key in (
        "world_T_port",
        "world_T_base",
        "world_T_tool",
        "world_T_weld_child",
        "world_T_sfp_tip",
        "tool_T_tcp",
        "weld_child_T_sfp_tip",
        "tool_T_weld_child",
        "tcp_T_sfp_tip",
        "desired_world_T_sfp_tip",
        "desired_world_T_tcp",
        "desired_base_T_tcp",
        "achieved_world_T_tcp",
        "virtual_world_T_sfp_tip",
        "actual_world_T_sfp_tip_after_payload_set",
    ):
        diagnostic_value = diagnostics.get(key)
        if isinstance(diagnostic_value, np.ndarray):
            print_transform(key, diagnostic_value)

    print(
        "  virtual_sfp_tip_position_error_m: "
        f"{float(np.linalg.norm(desired_world_T_sfp_tip[:3, 3] - virtual_world_T_sfp_tip[:3, 3])):.6g}"
    )
    print(
        "  actual_sfp_tip_position_error_m: "
        f"{float(np.linalg.norm(desired_world_T_sfp_tip[:3, 3] - actual_world_T_sfp_tip[:3, 3])):.6g}"
    )
    print()


def make_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--xml", required=True)
    p.add_argument(
        "--config",
        default=str(DEFAULT_CONFIG_PATH),
        help="JSON config file with optional include list.",
    )
    p.add_argument("--duration", type=float, default=0.0)
    p.add_argument("--log-period", type=float, default=1.0)
    p.add_argument("--print-model", action="store_true")
    return p


def main() -> int:
    args = make_parser().parse_args()
    cfg = load_json_config(args.config)

    model = mujoco.MjModel.from_xml_path(str(Path(args.xml).expanduser().resolve()))
    data = mujoco.MjData(model)

    if args.print_model:
        print_model_summary(model)
        return 0

    torque_mode = TorqueMode(cfg["torque_mode"])
    controlled = JointGroup(model, cfg["controlled_joints"], torque_mode=torque_mode)

    passive = PassiveJointGroup(
        model,
        cfg.get("passive_joints", []),
        mode=cfg.get("passive_mode", "free"),
    )

    controller = JointImpedanceController(
        controlled,
        JointImpedanceConfig(
            use_bias_compensation=bool(cfg["use_bias_compensation"]),
            torque_limits=np.asarray(cfg["torque_limits"], dtype=float),
            torque_rate_limits=np.asarray(cfg["torque_rate_limits"], dtype=float),
            clamp_to_joint_limits=True,
        ),
    )

    mujoco.mj_resetData(model, data)
    mujoco.mj_forward(model, data)

    # Snapshot passive joints first. This preserves the XML initial gripper state.
    # If passive_mode='freeze', these joints will stay exactly where the XML put them.
    passive.snapshot(data)

    q_target, preinsert_diagnostics = compute_preinsert_joint_target(
        model=model,
        data=data,
        controlled=controlled,
        home_q=np.asarray(cfg["ik_home_q"], dtype=float),
        port_body=cfg["preinsert_port_body"],
        tcp_site=cfg["preinsert_tcp_site"],
        sfp_tip_body=cfg["preinsert_sfp_tip_body"],
        tool_body=cfg["preinsert_tool_body"],
        weld_child_body=cfg["preinsert_weld_child_body"],
        height=float(cfg.get("preinsert_height", 0.05)),
        payload_root_body=cfg.get("preinsert_payload_root_body"),
        payload_root_freejoint=cfg.get("preinsert_payload_root_freejoint"),
    )
    print_preinsert_diagnostics(preinsert_diagnostics)

    qd_target = np.zeros(controlled.n)
    q_target = np.asarray(q_target, dtype=float)
    controller.reset(q_target.tolist())

    kp = np.asarray(cfg["kp"], dtype=float)
    kd = np.asarray(cfg["kd"], dtype=float)

    controlled.print_mapping("Controlled joints")
    passive.print_mapping("Passive joints")
    print()
    print("Fixed-target hold:")
    print(f"  config:                {Path(args.config).expanduser().resolve()}")
    print(f"  torque_mode:           {torque_mode.value}")
    print("  target_mode:           preinsert")
    print(f"  q_target:              {q_target.tolist()}")
    print(f"  passive_mode:          {passive.mode}")
    print(f"  bias_compensation:     {cfg['use_bias_compensation']}")
    print("  gripper controller:    none")
    print()
    print("Close viewer to stop.")
    print()

    t0 = time.time()
    last_log = -1e9

    with mujoco.viewer.launch_passive(model, data) as viewer:
        while viewer.is_running():
            t = time.time() - t0
            if args.duration > 0.0 and t >= args.duration:
                break

            dt = float(model.opt.timestep)

            # Clear external forces. We only write controlled torques below.
            data.qfrc_applied[:] = 0.0

            # Keep passive joints frozen if configured. This is intentionally not
            # a gripper controller; it is a generic kinematic freeze.
            passive.enforce(data)

            target = JointTarget.position(
                q_des=q_target.tolist(),
                qd_des=qd_target.tolist(),
                kp=kp.tolist(),
                kd=kd.tolist(),
                tau_ff=np.zeros(controlled.n).tolist(),
            )
            tau = controller.compute(data, target, dt)
            controlled.apply_torque(data, tau.tolist())

            mujoco.mj_step(model, data)

            # Enforce after integration too, so passive joints do not visibly drift.
            passive.enforce(data)
            mujoco.mj_forward(model, data)

            viewer.sync()

            if t - last_log >= args.log_period:
                last_log = t
                err = q_target - controlled.q(data)
                print(
                    "t={:7.2f} | q_err_norm={:10.6f} | max_abs_tau={:9.3f}".format(
                        t,
                        float(np.linalg.norm(err)),
                        float(np.max(np.abs(tau))),
                    )
                )

            time.sleep(dt)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
