#!/usr/bin/env python3
"""
Generic fixed-target hold demo.

Purpose:
  Test whether the MuJoCo-side joint-impedance layer can hold a fixed arm pose
  under gravity. With ``--target-mode preinsert`` the target is generated by
  solving IK for a TCP pose that places the carried SFP tip above the NIC-board
  port entrance.

Frame convention:
  ``A_T_B`` means "pose of frame B with respect to frame A"; it maps a point
  expressed in B into A.

Important scene frame names:
  ``sfp_port_0_link_entrance``:
    port entrance body; this is the desired SFP-tip frame basis.
  ``gripper_tcp``:
    MuJoCo site corresponding to the AIC/Tesseract ``gripper/tcp`` IK target.
  ``ati/tool_link``:
    robot-side tool body.
  ``lc_plug_link``:
    weld child body for the held plug/cable subtree.
  ``sfp_tip_link``:
    SFP plug tip body that should line up with the port entrance.
  ``cable_end_0`` / ``cable_end_0_free``:
    payload root body/freejoint. After IK, the freejoint is moved so the visible
    plug agrees with the kinematic SFP-tip target.

Correct pre-insertion transform chain:
  The initial free-body cable pose in the XML may not already satisfy the weld,
  so do not derive ``tcp_T_sfp_tip`` directly from the raw current
  ``world_T_tcp`` and ``world_T_sfp_tip``. Instead derive it from topology:

    ``tool_T_tcp = inv(world_T_tool) @ world_T_tcp``

    ``weld_child_T_sfp_tip =
        inv(world_T_weld_child) @ world_T_sfp_tip``

    ``tcp_T_sfp_tip =
        inv(tool_T_tcp) @ tool_T_weld_child @ weld_child_T_sfp_tip``

  where ``tool_T_weld_child`` comes from the MuJoCo weld equality between
  ``ati/tool_link`` and ``lc_plug_link``.

Desired SFP-tip pose:
  The pre-insertion target uses the port entrance orientation and shifts upward
  in world Z:

    ``desired_world_T_sfp_tip = world_T_port``

    ``desired_world_T_sfp_tip.p.z += preinsert_height``

IK target:
  ``EnsemblRobot.ComputeIK`` targets ``gripper/tcp``, so convert the desired
  SFP-tip pose into a TCP pose before calling IK:

    ``desired_world_T_tcp =
        desired_world_T_sfp_tip @ inv(tcp_T_sfp_tip)``

  The AIC robot model is expressed in base coordinates. Align MuJoCo world to
  the EnsemblRobot base at ``ik_home_q``:

    ``world_T_base = world_T_tcp_home @ inv(base_T_tcp_home)``

    ``desired_base_T_tcp =
        inv(world_T_base) @ desired_world_T_tcp``

  Then choose the IK solution closest to ``ik_home_q``.

Run from the AIC pixi shell:
  PYTHONPATH=/home/rmalhan/Software/ws_aic/src/aic/aic_utils/aic_mujoco:/home/rmalhan/Software/ws_aic/src/aic/aic_model \
  python3 aic_utils/aic_mujoco/scripts/hold_fixed_target.py \
    --xml /home/rmalhan/Software/ws_aic/src/aic/aic_utils/aic_mujoco/mjcf/scene.xml \
    --config /home/rmalhan/Software/ws_aic/src/aic/aic_utils/aic_mujoco/configs/aic_ur5e_hold.json \
    --target-mode preinsert \
    --preinsert-height 0.05
"""

from __future__ import annotations

import argparse
import json
import time
from pathlib import Path
from typing import Any

import mujoco
import mujoco.viewer
import numpy as np

from aic_mujoco.joints import (
    JointGroup,
    PassiveJointGroup,
    TorqueMode,
    print_model_summary,
)
from aic_mujoco.controllers import (
    JointImpedanceConfig,
    JointImpedanceController,
    JointTarget,
)
from aic_mujoco.utils import (
    compute_preinsert_joint_target,
    print_transform,
)

DEFAULT_CONFIG = {
    "controlled_joints": [
        "shoulder_pan_joint",
        "shoulder_lift_joint",
        "elbow_joint",
        "wrist_1_joint",
        "wrist_2_joint",
        "wrist_3_joint",
    ],
    "passive_joints": ["gripper/left_finger_joint", "gripper/right_finger_joint"],
    "passive_mode": "freeze",
    "torque_mode": "actuator_ctrl",
    "target_mode": "initial",
    "target_q": None,
    "ik_home_q": [-0.1597, -1.3542, -1.6648, -1.6933, 1.5710, 1.4110],
    "preinsert_port_body": "sfp_port_0_link_entrance",
    "preinsert_tcp_site": "gripper_tcp",
    "preinsert_sfp_tip_body": "sfp_tip_link",
    "preinsert_tool_body": "ati/tool_link",
    "preinsert_weld_child_body": "lc_plug_link",
    "preinsert_payload_root_body": "cable_end_0",
    "preinsert_payload_root_freejoint": "cable_end_0_free",
    "preinsert_height": 0.05,
    "kp": [100.0, 100.0, 100.0, 50.0, 50.0, 50.0],
    "kd": [40.0, 40.0, 40.0, 15.0, 15.0, 15.0],
    "torque_limits": [120.0, 120.0, 120.0, 60.0, 60.0, 60.0],
    "torque_rate_limits": [1200.0, 1200.0, 1200.0, 600.0, 600.0, 600.0],
    "use_bias_compensation": True,
}


def load_config(path: str | None) -> dict[str, Any]:
    cfg = dict(DEFAULT_CONFIG)
    if path is not None:
        with open(Path(path).expanduser(), "r", encoding="utf-8") as f:
            user_cfg = json.load(f)
        cfg.update(user_cfg)
    return cfg


def csv_list(text: str) -> list[str]:
    return [x.strip() for x in text.split(",") if x.strip()]


def csv_floats(text: str) -> list[float]:
    return [float(x.strip()) for x in text.replace(" ", ",").split(",") if x.strip()]


def print_preinsert_diagnostics(
    diagnostics: dict[str, np.ndarray | str | float | int | None],
) -> None:
    desired_world_T_sfp_tip = diagnostics["desired_world_T_sfp_tip"]
    virtual_world_T_sfp_tip = diagnostics["virtual_world_T_sfp_tip"]
    actual_world_T_sfp_tip = diagnostics["actual_world_T_sfp_tip_after_payload_set"]
    assert isinstance(desired_world_T_sfp_tip, np.ndarray)
    assert isinstance(virtual_world_T_sfp_tip, np.ndarray)
    assert isinstance(actual_world_T_sfp_tip, np.ndarray)

    print("Pre-insertion IK request:")
    for key in (
        "port_body",
        "tcp_site",
        "sfp_tip_body",
        "tool_body",
        "weld_child_body",
        "tcp_T_sfp_tip_source",
        "payload_root_body",
        "payload_root_freejoint",
        "height",
        "solution_count",
    ):
        print(f"  {key}: {diagnostics[key]}")
    print(f"  desired_world_p_sfp_tip: {desired_world_T_sfp_tip[:3, 3].tolist()}")
    print(f"  desired_world_p_tcp: {diagnostics['desired_world_T_tcp'][:3, 3].tolist()}")
    print(f"  desired_base_p_tcp: {diagnostics['desired_base_T_tcp'][:3, 3].tolist()}")

    for key in (
        "world_T_port",
        "world_T_base",
        "world_T_tool",
        "world_T_weld_child",
        "world_T_sfp_tip",
        "tool_T_tcp",
        "weld_child_T_sfp_tip",
        "tool_T_weld_child",
        "tcp_T_sfp_tip",
        "desired_world_T_sfp_tip",
        "desired_world_T_tcp",
        "desired_base_T_tcp",
        "achieved_world_T_tcp",
        "virtual_world_T_sfp_tip",
        "actual_world_T_sfp_tip_after_payload_set",
    ):
        transform = diagnostics.get(key)
        if isinstance(transform, np.ndarray):
            print_transform(key, transform)

    print(
        "  virtual_sfp_tip_position_error_m: "
        f"{float(np.linalg.norm(desired_world_T_sfp_tip[:3, 3] - virtual_world_T_sfp_tip[:3, 3])):.6g}"
    )
    print(
        "  actual_sfp_tip_position_error_m: "
        f"{float(np.linalg.norm(desired_world_T_sfp_tip[:3, 3] - actual_world_T_sfp_tip[:3, 3])):.6g}"
    )
    print()


def make_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser()
    p.add_argument("--xml", required=True)
    p.add_argument("--config", default=None, help="Optional JSON config file.")

    # CLI overrides. Use these only when you don't want to edit JSON.
    p.add_argument("--controlled-joints", type=csv_list, default=None)
    p.add_argument("--passive-joints", type=csv_list, default=None)
    p.add_argument("--passive-mode", choices=["free", "freeze"], default=None)
    p.add_argument("--torque-mode", choices=[m.value for m in TorqueMode], default=None)
    p.add_argument(
        "--target-mode",
        choices=["initial", "explicit", "preinsert"],
        default=None,
        help="Choose initial hold target, explicit target_q, or home-biased pre-insertion IK.",
    )
    p.add_argument("--target-q", type=csv_floats, default=None)
    p.add_argument("--ik-home-q", type=csv_floats, default=None)
    p.add_argument("--preinsert-port-body", default=None)
    p.add_argument("--preinsert-tcp-site", default=None)
    p.add_argument("--preinsert-sfp-tip-body", default=None)
    p.add_argument("--preinsert-tool-body", default=None)
    p.add_argument("--preinsert-weld-child-body", default=None)
    p.add_argument("--preinsert-payload-root-body", default=None)
    p.add_argument("--preinsert-payload-root-freejoint", default=None)
    p.add_argument(
        "--preinsert-height",
        type=float,
        default=None,
        help="World-Z height above the port entrance for the SFP tip target.",
    )
    p.add_argument("--no-bias-comp", action="store_true")
    p.add_argument("--torque-mode-fallback-qfrc", action="store_true")
    p.add_argument("--duration", type=float, default=0.0)
    p.add_argument("--log-period", type=float, default=1.0)
    p.add_argument("--print-model", action="store_true")
    return p


def main() -> int:
    args = make_parser().parse_args()
    cfg = load_config(args.config)

    if args.controlled_joints is not None:
        cfg["controlled_joints"] = args.controlled_joints
    if args.passive_joints is not None:
        cfg["passive_joints"] = args.passive_joints
    if args.passive_mode is not None:
        cfg["passive_mode"] = args.passive_mode
    if args.torque_mode is not None:
        cfg["torque_mode"] = args.torque_mode
    if args.target_mode is not None:
        cfg["target_mode"] = args.target_mode
    if args.target_q is not None:
        cfg["target_q"] = args.target_q
        cfg["target_mode"] = "explicit"
    if args.ik_home_q is not None:
        cfg["ik_home_q"] = args.ik_home_q
    if args.preinsert_port_body is not None:
        cfg["preinsert_port_body"] = args.preinsert_port_body
    if args.preinsert_tcp_site is not None:
        cfg["preinsert_tcp_site"] = args.preinsert_tcp_site
    if args.preinsert_sfp_tip_body is not None:
        cfg["preinsert_sfp_tip_body"] = args.preinsert_sfp_tip_body
    if args.preinsert_tool_body is not None:
        cfg["preinsert_tool_body"] = args.preinsert_tool_body
    if args.preinsert_weld_child_body is not None:
        cfg["preinsert_weld_child_body"] = args.preinsert_weld_child_body
    if args.preinsert_payload_root_body is not None:
        cfg["preinsert_payload_root_body"] = args.preinsert_payload_root_body
    if args.preinsert_payload_root_freejoint is not None:
        cfg["preinsert_payload_root_freejoint"] = args.preinsert_payload_root_freejoint
    if args.preinsert_height is not None:
        cfg["preinsert_height"] = args.preinsert_height
    if args.no_bias_comp:
        cfg["use_bias_compensation"] = False

    model = mujoco.MjModel.from_xml_path(str(Path(args.xml).expanduser().resolve()))
    data = mujoco.MjData(model)

    if args.print_model:
        print_model_summary(model)
        return 0

    torque_mode = TorqueMode(cfg["torque_mode"])
    try:
        controlled = JointGroup(
            model, cfg["controlled_joints"], torque_mode=torque_mode
        )
    except RuntimeError:
        if not args.torque_mode_fallback_qfrc:
            raise
        print("WARNING: actuator_ctrl mapping failed; falling back to qfrc_applied.")
        torque_mode = TorqueMode.QFRC_APPLIED
        controlled = JointGroup(
            model, cfg["controlled_joints"], torque_mode=torque_mode
        )

    passive = PassiveJointGroup(
        model,
        cfg.get("passive_joints", []),
        mode=cfg.get("passive_mode", "free"),
    )

    controller = JointImpedanceController(
        controlled,
        JointImpedanceConfig(
            use_bias_compensation=bool(cfg["use_bias_compensation"]),
            torque_limits=np.asarray(cfg["torque_limits"], dtype=float),
            torque_rate_limits=np.asarray(cfg["torque_rate_limits"], dtype=float),
            clamp_to_joint_limits=True,
        ),
    )

    mujoco.mj_resetData(model, data)
    mujoco.mj_forward(model, data)

    # Snapshot passive joints first. This preserves the XML initial gripper state.
    # If passive_mode='freeze', these joints will stay exactly where the XML put them.
    passive.snapshot(data)

    target_mode = cfg.get("target_mode", "initial")
    if target_mode == "preinsert":
        q_target, preinsert_diagnostics = compute_preinsert_joint_target(
            model=model,
            data=data,
            controlled=controlled,
            home_q=np.asarray(cfg["ik_home_q"], dtype=float),
            port_body=cfg["preinsert_port_body"],
            tcp_site=cfg["preinsert_tcp_site"],
            sfp_tip_body=cfg["preinsert_sfp_tip_body"],
            tool_body=cfg["preinsert_tool_body"],
            weld_child_body=cfg["preinsert_weld_child_body"],
            height=float(cfg.get("preinsert_height", 0.05)),
            payload_root_body=cfg.get("preinsert_payload_root_body"),
            payload_root_freejoint=cfg.get("preinsert_payload_root_freejoint"),
        )
        print_preinsert_diagnostics(preinsert_diagnostics)
    elif target_mode == "explicit":
        q_target = np.asarray(cfg["target_q"], dtype=float)
        controlled.set_q(data, q_target, zero_velocity=True)
    else:
        q_target = controlled.q(data).copy()

    qd_target = np.zeros(controlled.n)
    controller.reset(q_target)

    kp = np.asarray(cfg["kp"], dtype=float)
    kd = np.asarray(cfg["kd"], dtype=float)

    controlled.print_mapping("Controlled joints")
    passive.print_mapping("Passive joints")
    print()
    print("Fixed-target hold:")
    print(f"  torque_mode:           {torque_mode.value}")
    print(f"  target_mode:           {target_mode}")
    print(f"  q_target:              {q_target.tolist()}")
    print(f"  passive_mode:          {passive.mode}")
    print(f"  bias_compensation:     {cfg['use_bias_compensation']}")
    print("  gripper controller:    none")
    print()
    print("Close viewer to stop.")
    print()

    t0 = time.time()
    last_log = -1e9

    with mujoco.viewer.launch_passive(model, data) as viewer:
        while viewer.is_running():
            t = time.time() - t0
            if args.duration > 0.0 and t >= args.duration:
                break

            dt = float(model.opt.timestep)

            # Clear external forces. We only write controlled torques below.
            data.qfrc_applied[:] = 0.0

            # Keep passive joints frozen if configured. This is intentionally not
            # a gripper controller; it is a generic kinematic freeze.
            passive.enforce(data)

            target = JointTarget.position(
                q_des=q_target,
                qd_des=qd_target,
                kp=kp,
                kd=kd,
                tau_ff=np.zeros(controlled.n),
            )
            tau = controller.compute(data, target, dt)
            controlled.apply_torque(data, tau)

            mujoco.mj_step(model, data)

            # Enforce after integration too, so passive joints do not visibly drift.
            passive.enforce(data)
            mujoco.mj_forward(model, data)

            viewer.sync()

            if t - last_log >= args.log_period:
                last_log = t
                err = q_target - controlled.q(data)
                print(
                    "t={:7.2f} | q_err_norm={:10.6f} | max_abs_tau={:9.3f}".format(
                        t,
                        float(np.linalg.norm(err)),
                        float(np.max(np.abs(tau))),
                    )
                )

            time.sleep(dt)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
