from __future__ import annotations

from typing import Any

from mujoco import MjData, MjModel


class PassiveViewer:
    def __enter__(self) -> PassiveViewer: ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    def is_running(self) -> bool: ...
    def sync(self) -> None: ...


def launch_passive(model: MjModel, data: MjData) -> PassiveViewer: ...
